title: EVM Networks
description: >- # this means to ignore newlines until "baseurl:"
  A site to share information about EVM powered networks, especially their ChainID and NetworkID.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chainid.network" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

# theme: just-the-docs
plugins:
  - jekyll-feed

# --- just-the-docs theme ---

# Enable or disable the site search
search_enabled: false

# Aux links for the upper right navigation
aux_links:
  "GitHub: ethereum-lists/chains":
    - "//github.com/ethereum-lists/chains"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil
